name: ASCILL_job

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      
      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "always state away , iam a dragon" >> dragon.txt
      - name: test  File exsit 
        run: grep -i  "dragon" dragon.txt
      - name: Display Generated File
        run: cat dragon.txt